version: '3.8'

services:
#DEV Drupal(Apache) + MySQL
  drupal:
    image: drupal:10-apache
    container_name: drupal_dev
    restart: always
    volumes:
      - devData:/var/www/html/
    ports:
      - 8080:80
    dns_search:
      - svc.local
      - dev.local
    networks:
      development_net:
        ipv4_address: 172.40.0.5
    depends_on:
      - mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drupal.rule=Host(`dev.localhost`)"
      - "traefik.http.routers.drupal.service=drupal"
      - "traefik.http.services.drupal.loadbalancer.server.port=80"

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    volumes:
      - devdb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      development_net:
        ipv4_address: 172.40.0.6

#------------------------------------------------------------#

#WIP PROD NGINX + POSTGRES
  nginxProd:
    image: 'bitnami/nginx:latest'
    container_name: nginxprod
    restart: always
    volumes:
      - ./Production/server-block.conf:/opt/bitnami/nginx/conf/server_blocks/server-block.conf  # Configuración de Nginx
      - prodData:/app
    ports:
      - 8081:80
    extra_hosts:
      - "prod.local:172.30.0.5"
      - "ns1.svc.local:172.20.0.6"
      - "svc.local:172.20.0.6"
    networks:
      production_net:
        ipv4_address: 172.30.0.5
    depends_on:
      - postgresql


  postgresql:
    image: 'bitnami/postgresql:latest'
    container_name: postgresql
    restart: always
    volumes:
      - proddb:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=drupal
      - POSTGRESQL_USERNAME=drupal
      - POSTGRESQL_PASSWORD=password
    networks:
      production_net:
        ipv4_address: 172.30.0.8

#------------------------------------------------------------#

# NAS

  nasServ:
    image: debian:latest
    container_name: nasserv
    restart: always
    command: bash ./backups/startup.sh
    environment:
      MYSQL_ROOT_PASSWORD: password           # Contraseña de MySQL
      POSTGRES_PASSWORD: postgrespassword         # Contraseña de PostgreSQL
    volumes:
      - ./nas_data/backups:/backups               # Monta el directorio de copias de seguridad
    networks:
      services_net:
        ipv4_address: 172.20.0.5
    ports:
      - "873:873"
    depends_on:
      - bind9
    tty: true


  # DNS WIP
  bind9:
    image: internetsystemsconsortium/bind9:9.20
    container_name: bind9
    restart: always
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./bind/config:/etc/bind                   # Configuración principal
      - ./bind/config/zones:/etc/bind/zones       # Archivos de zona      
      - ./bind/logs:/var/log/named                # Logs
    environment:
      - TZ=Europe/Madrid
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      services_net:
        ipv4_address: 172.20.0.6
      development_net:
      production_net:


#------------------------------------------------------------#

# SSH WIP
  sshServices:     #Por par de claves
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh-service
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - USER_NAME=userserv
      - PUBLIC_KEY_FILE=/config/keys/id_rsa.pub 
      - PUBLIC_KEY_DIR=/config/keys
      - SUDO_ACCESS=false
      - PASSWORD_ACCESS=false 
      - LOG_STDOUT=true
    volumes:
      - ./ssh/services/sshServ.config:/config/sshd_config
      - ./ssh/services/startServ.sh:/custom-cont-init.d/start.sh
      - ./ssh/services/keys:/config/keys
    networks:
      services_net:
        ipv4_address: 172.20.0.10
    restart: unless-stopped
    # Cuando pida la passphrase en esa clave es Services

  sshDev:     #Por login
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh-Dev
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - USER_NAME=userdev
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=supersecreto
      - LOG_STDOUT=true
    volumes:
      - ./ssh/development/sshDev.config:/config/sshd_config
      - ./ssh/development/startDev.sh:/custom-cont-init.d/start.sh
    networks:
      development_net:
        ipv4_address: 172.40.0.10   # IP fija dentro de la red de servicios
    restart: unless-stopped   
  
# Firewall 
  firewall:
    image: alpine:latest
    container_name: firewall
    restart: always
    sysctls:
      net.ipv4.ip_forward: "1"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./firewall/startup.sh:/firewall.sh
    networks:
      development_net:
        ipv4_address: 172.40.0.15
      production_net:
        ipv4_address: 172.30.0.15
      services_net:
        ipv4_address: 172.20.0.15
      vpn_net:
        ipv4_address: 172.10.0.15
    command: sh -c "sh /firewall.sh"

#------------------------------------------------------------#
# VPN 
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/udp"
    environment:
      - EASYRSA_BATCH=1
    volumes:
      - ovpndata:/etc/openvpn
      - ./vpn/start.sh:/start.sh
      - ./vpn/ovpn-data/clients:/etc/openvpn/clients
    entrypoint: ["/bin/sh", "/start.sh"]
    restart: always
    command: ovpn_run
    networks:
      vpn_net:
        ipv4_address: 172.10.0.100

#------------------------------------------------------------#

networks:
  services_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
  production_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
  development_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/24
  vpn_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/24

#------------------------------------------------------------#

volumes:
  devData:
  devdb:
  prodData:
  proddb:
  dnscache:
  dnslogs:
  ovpndata:
