upstream php_fpm_pool {  
    server phpfpm1:9000;
    server phpfpm2:9000;
}

server {
    listen 0.0.0.0:80;
    server_name dev.local;

    root /app/web;
    index index.php index.html index.htm;

    # Regla principal para manejar URLs
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Servir archivos estáticos directamente sin pasar por PHP
    location ~* \.(jpg|jpeg|gif|png|css|js|ico|woff2|woff|ttf|svg|mp4|webp)$ {
        expires max;
        add_header Cache-Control "public, no-transform";
        log_not_found off;
        access_log off;
    }

    # Configuración para PHP
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php_fpm_pool;  # El enlace a PHP-FPM dentro del contenedor
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
    }

    # Bloquear acceso a archivos ocultos (como .htaccess)
    location ~ /\.ht {
        deny all;
    }
}
