server {
    listen 0.0.0.0:80;
    server_name dev.local;

    root /app/web;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(jpg|jpeg|gif|png|css|js|ico|woff2|woff|ttf|svg|mp4|webp)$ {
        expires max;
        add_header Cache-Control "public, no-transform";
        log_not_found off;
        access_log off;
    }

    location ~ /\.ht {
        deny all;
    }
}